import type { NextPage } from "next";
import Head from "next/head";
import SideBar from "../components/SideBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Support Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <SideBar/>
    </>
  );
};

export default Home;


